name: "Hydra"
port: ":4100"
env: "dev"
debug: true
logger:
  logLvl: "debug"
  logReq: true
  logResp: true
statsEnabled: true
remoteProfiler:
  enabled: false
  profilerURL: "http://pyroscope:4040"
remoteTrace:
  enabled: true
  traceAgent: "jaeger-tracing-agent.monitoring:6831"
  traceCollector: "http://jaeger-tracing-collector.monitoring:14268/api/traces"
  ratio: 1
nats:
  clusterId: "tech4edu"
  address: "nats-streaming-client.nats-streaming"
redis:
  host: "redis-master.databases:6379"
  password: "NGtKOGFRWXR3endnS3NTcQ=="
cockroachdb:
  uri: "cG9zdGdyZXM6Ly90ZWNoNGVkdTpNNjc2M3pVbnI4dEJkd3lkQGNvY2tyb2FjaGRiLmRhdGFiYXNlczoyNjI1Ny9kZXZtbWxhYmVsP3Bvb2xfbWF4X2Nvbm5zPTUwJnBvb2xfbWF4X2Nvbm5fbGlmZXRpbWU9NW0mcG9vbF9oZWFsdGhfY2hlY2tfcGVyaW9kPTMwcw=="
  migrationPath: "file://./migrations"
jwt:
  expiry: 365h
  encryptionKey: "NsdXN0dZXIubG9jYWw6Mjcww"
  audience: "mmprinting"
  issuer: "hydra"
firebase:
  configPath: /secrets/firebase-adminsdk-creds.json
s3Storage:
  region: us-east-1
  bucket: 'mm-dev'
  accessKey: "AEdOz31AzzxK7Xjs4OuH"
  secretKey: "445LyVdtKroiQUBfa0YLWwjr3shQTj4VbjtJSGfE"
  endpoint: "http://s3.hagi.dev"
