-- mã thông số in	Mã tài liệu hướng dẫn máy in	Mã bản in nguồn 	Ngày hiệu lực	Tên bản in	Mã sản phẩm ( (chọn nhiều sản phẩm ngăn cách bằng dấu ;)	MÃ SẢN PHẨM NỘI BỘ 	Chu kỳ in (giờ gian trung bình của một lượt in)	Thời gian chuẩn bị (thời gian sản xuất thử)	TÊN MÀU MỰC	Tên loại mực	Số thứ tự in	Mã phim 	Mã màu mực  (trên from hướng dẫn công việc của A Nam là mã màu)	Tình trạng mực (đã có /chưa có )	Diện tích phủ mực	dung môi	nhiệt độ sấy	thời gian sấy	Ghi chú mực in	Mã khung	Thông số lụa	Khoảng cách khung in với bản in	cách in(thuận/ngược)	 cứng dao	Độ bén dao	Độ nghiêng dao	Tốc độ dao	Tốc độ		sản phẩm nguồn	bản in nguồn	LSX đã gán
ALTER TABLE production_order_device_config
    ADD COLUMN ma_thong_so_may varchar(250) ,
    ADD COLUMN ma_tai_lieu_huong_dan varchar(250),
    ADD COLUMN ngay_hieu_luc date,
    ADD COLUMN stage_id varchar(250),
    ADD COLUMN ma_san_pham varchar(250),
    ADD COLUMN ma_san_pham_noi_bo varchar(250),
    ADD COLUMN chu_ky_in varchar(250),
    ADD COLUMN thoi_gian_chuan_bi varchar(250),
    ADD COLUMN ten_mau_muc varchar(250),
    ADD COLUMN ten_loai_muc varchar(250),
    ADD COLUMN so_thu_tu_in varchar(250),
    ADD COLUMN ma_phim varchar(250),
    ADD COLUMN ma_mau_muc varchar(250),
    ADD COLUMN tinh_trang_muc varchar(250),
    ADD COLUMN dien_tich_phu_muc varchar(250),
    ADD COLUMN dung_moi varchar(250),
    ADD COLUMN nhiet_do_say varchar(250),
    ADD COLUMN thoi_gian_say varchar(250),
    ADD COLUMN ghi_chu varchar(250),
    ADD COLUMN ma_khung varchar(250),
    ADD COLUMN thong_so_lua varchar(250),
    ADD COLUMN khoang_cach_khung_in_ban_in varchar(250),
    ADD COLUMN cach_in varchar(250),
    ADD COLUMN cung_dao varchar(250),
    ADD COLUMN do_ben_dao varchar(250),
    ADD COLUMN do_nghieng_dao varchar(250),
    ADD COLUMN toc_do_dao varchar(250),
    ADD COLUMN toc_do varchar(250),
    ADD COLUMN san_pham_nguon varchar(250),
    ADD COLUMN ban_in_nguon varchar(250);