replicaCount: 3

storageClass: ""

streaming:
  id: flamingo-group
  debug:
    enabled: true
    trace: true
  ftGroup: flamingo-group

image:
  repository: nats-streaming
  tag: 0.17.0
  pullPolicy: IfNotPresent

fullnameOverride: "nats-streaming"

metrics:
  image:
    repository: synadia/prometheus-nats-exporter
    tag: 0.6.0
  args:
    - -serverz
    - -channelz
  podAnnotations:
    prometheus.io/port: "7777"
    prometheus.io/scrape: "true"

testFt:
  enabled: false

statefulset: {}
