name: "Aurora"
port: ":5100"
env: "dev"
debug: true
logger:
  logLvl: "debug"
  logReq: true
  logResp: true
statsEnabled: true
remoteProfiler:
  enabled: true
  profilerURL: "http://pyroscope.monitoring"
remoteTrace:
  enabled: true
  traceAgent: "jaeger-tracing-agent.monitoring:6831"
  traceCollector: "http://jaeger-tracing-collector.monitoring:14268/api/traces"
  ratio: 1
zalo:
  oaCallbackUrl: "https://mmlabel.buonho.vn/aurora/oa/callback"
  oaAccessTokeUrl: "https://oauth.zaloapp.com/v4/oa/access_token"
  oaPermissionUrl: "https://oauth.zaloapp.com/v4/oa/permission"
nats:
  clusterId: "mm-printing"
  address: "nats-streaming-client.nats-streaming"
cockroachdb:
  uri: "cG9zdGdyZXM6Ly90ZWNoNGVkdTp0ZWNoNGVkdUBjb2Nrcm9hY2hkYi5kYXRhYmFzZXM6MjYyNTcvcG9zdGdyZXM/cG9vbF9tYXhfY29ubnM9NTAmcG9vbF9tYXhfY29ubl9saWZldGltZT01bSZwb29sX2hlYWx0aF9jaGVja19wZXJpb2Q9MzBz"
  migrationPath: "file://./migrations"
iotHub:
  maxIdleConnections: 100
  requestTimeout: 300
  connectTimeout: 5
jwt:
  expiry: 1h
  encryptionKey : "KJAfbaiufbcHCVBAHDc"
  audience: "mm-printing"
  issuer: "hydra"
redis:
  host: "redis-master.databases:6379"
  password: "NGtKOGFRWXR3endnS3NTcQ=="
websockerDocsDir: "/ws-docs/"
defaultPondInitDevice:
  otherDevices:
    'paddle_wheel':
      '1':
        '13:22:00': 300
        '16:00:00': 4500
        '06:00:00': 4500
        '11:00:00': 4500
        '20:00:00': 11700
      '2':
        '10:49:00': 180
        '23:15:00': 2700
        '02:00:00': 14400
        '06:00:00': 1800
        '11:00:00': 1800
        '17:15:00': 13500
        '12:15:00': 1800
        '07:15:00': 1800
      '3':
        '10:49:00': 240
        '00:00:00': 3600
        '21:00:00': 6300
        '02:00:00': 3600
        '06:00:00': 2700
        '11:00:00': 2700
        '04:00:00': 7200
        '14:00:00': 3600
        '09:00:00': 3600
        '19:00:00': 3600
    'syphon_pump':
      '1':
        '22:45:00': 4500
        '06:45:00': 1800
        '03:00:00': 3600
        '11:45:00': 1800
        '16:45:00': 1800
    'air_blower':
      '1':
        '00:00:00': 0
  feederParams:
    feederSpeed: 20
    feedingSchedule:
      '17:15:00': 21
      '23:15:00': 21
      '12:15:00': 16
      '04:00:00': 26
      '07:15:00': 16
    feedingActiveIntervalInMinute: 30
    feedingDeactiveIntervalInMinute: 30
    totalFeedAmount: 19
    semi: 'semi'
