apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: monitoring-gateway
  namespace: monitoring
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https-secondary
      protocol: HTTPS
    hosts:
    - "grafana-prod.tomota.vn"
    tls:
      credentialName: cert-grafana-prod.tomota.vn
      mode: SIMPLE
      privateKey: sds
      serverCertificate: sds
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: monitoring-ingress
  namespace: monitoring
spec:
  hosts:
  - "grafana-prod.tomota.vn"
  gateways:
  - monitoring-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: grafana
        port:
          number: 80
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: grafana-prod.tomota.vn
  namespace: istio-system
spec:
  commonName: grafana-prod.tomota.vn
  dnsNames:
  - grafana-prod.tomota.vn
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: cert-grafana-prod.tomota.vn

