apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aurora.fullname" . }}-config
  labels:
  {{- include "aurora.labels" . | nindent 4 }}
data:
  aurora.config.yaml: |-
{{ printf "configs/%s/aurora.config.yaml" .Values.env  | .Files.Get  | indent 4 }}
