apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  profile: default

  meshConfig:
    outboundTrafficPolicy:
      mode: ALLOW_ANY
    enableAutoMtls: false
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON

  components:
    pilot:
      k8s:
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 1Gi
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          env:
            - name: ISTIO_META_ROUTER_MODE
              value: "sni-dnat"
          service:
            ports:
              - port: 15021
                targetPort: 15021
                name: status-port
              - port: 80
                targetPort: 8080
                name: http
              - port: 443
                targetPort: 8443
                name: https
  values:
    global:
      proxy:
        holdApplicationUntilProxyStarts: true
      tracer:
        zipkin:
          address: jaeger-tracing-collector.monitoring:9411
