apiVersion: v1
kind: Service
metadata:
  name: {{ include "nats-streaming.fullname" . }}-client
  labels:
{{ include "nats-streaming.labels" . | indent 4 }}
spec:
  clusterIP: None
  ports:
    - name: tcp-client
      port: 4222
      targetPort: client
  selector:
    app.kubernetes.io/name: {{ include "nats-streaming.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
