apiVersion: v1
kind: Service
metadata:
  name: {{ include "nats-streaming.fullname" . }}-cluster
  labels:
{{ include "nats-streaming.labels" . | indent 4 }}
spec:
  clusterIP: None
  ports:
    - name: tcp-cluster
      port: 6222
      targetPort: cluster
  selector:
    app.kubernetes.io/name: {{ include "nats-streaming.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
