apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nats-streaming.fullname" . }}
  labels:
{{ include "nats-streaming.labels" . | indent 4 }}
spec:
  serviceName: nats-streaming
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nats-streaming.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nats-streaming.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
{{- if .Values.metrics.podAnnotations }}
{{ toYaml .Values.metrics.podAnnotations | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: client
              containerPort: 4222
            - name: cluster
              containerPort: 6222
            - name: monitoring
              containerPort: 8222
          args:
            - "-sc"
            - "/etc/stan-config/stan.conf"
          livenessProbe:
            httpGet:
              path: /
              port: monitoring
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
          volumeMounts:
            - name: config-volume
              mountPath: /etc/stan-config
            - name: datadir
              mountPath: /data/stan/store
        {{- with .Values.statefulset.resources }}
          resources: {{- toYaml . | nindent 12 }}
        {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: "{{ template "nats-streaming.name" . }}"
                  app.kubernetes.io/instance: {{ .Release.Name | quote }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "nats-streaming.fullname" . }}
        - name: datadir
          persistentVolumeClaim:
            claimName: datadir
  volumeClaimTemplates:
    - metadata:
        name: datadir
        labels:
          app.kubernetes.io/name: {{ include "nats-streaming.name" . }}
          app.kubernetes.io/instance: {{ .Release.Name }}
      spec:
        storageClassName: {{ .Values.storageClass }}
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
