apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mm-printing/file"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi