apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "iot.fullname" . }}-config
  labels:
  {{- include "iot.labels" . | nindent 4 }}
data:
  iot.config.yaml: |-
{{ printf "configs/%s/iot.config.yaml" .Values.env  | .Files.Get  | indent 4 }}
