name: "Iot Service"
port: ":7100"
env: "dev"
debug: false
logger:
  logLvl: "info"
  logReq: false
  logResp: false
statsEnabled: true
remoteProfiler:
  enabled: true
  profilerURL: "http://pyroscope.monitoring"
remoteTrace:
  enabled: true
  traceAgent: "jaeger-tracing-agent.monitoring:6831"
  traceCollector: "http://jaeger-tracing-collector.monitoring:14268/api/traces"
  ratio: 1
zalo:
  oaCallbackUrl: "https://mmlabel.buonho.vn/iot/oa/callback"
  oaAccessTokeUrl: "https://oauth.zaloapp.com/v4/oa/access_token"
  oaPermissionUrl: "https://oauth.zaloapp.com/v4/oa/permission"
nats:
  clusterId: "tech4edu"
  address: "nats-streaming-client.nats-streaming"
cockroachdb:
  uri: "cG9zdGdyZXM6Ly90ZWNoNGVkdTpNNjc2M3pVbnI4dEJkd3lkQGNvY2tyb2FjaGRiLmRhdGFiYXNlczoyNjI1Ny9kZXZtbWxhYmVsP3Bvb2xfbWF4X2Nvbm5zPTUwJnBvb2xfbWF4X2Nvbm5fbGlmZXRpbWU9NW0mcG9vbF9oZWFsdGhfY2hlY2tfcGVyaW9kPTMwcw=="
  migrationPath: "file://./migrations"
iotHub:
  maxIdleConnections: 100
  requestTimeout: 300
  connectTimeout: 5
mqtt:
  host: "103.252.72.219"
  port: 31883
  username: "user1"
  password: "123"
jwt:
  expiry: 365h
  encryptionKey : "NsdXN0dZXIubG9jYWw6Mjcww"
  audience: "mmprinting"
  issuer: "hydra"
redis:
  host: "redis-master.databases:6379"
  password: "NGtKOGFRWXR3endnS3NTcQ=="
websockerDocsDir: "/ws-docs/"
