apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hydra.fullname" . }}-config
  labels:
  {{- include "hydra.labels" . | nindent 4 }}
data:
  hydra.config.yaml: |-
{{ printf "configs/%s/hydra.config.yaml" .Values.env  | .Files.Get  | indent 4 }}
