apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hydra.fullname" . }}-secret
  labels:
  {{- include "hydra.labels" . | nindent 4 }}
data:
  firebase-adminsdk-creds.json: |-
    {{ printf "configs/%s/firebase-adminsdk-creds.json" .Values.env  | .Files.Get  | b64enc }}
