architecture: "standalone"
auth:
  password: "4kJ8aQYtwzwgKsSq"

image:
  repository: bitnami/redis
  tag: 5.0.9

master:
  persistence:
    enabled: false
volumePermissions:
  enabled: false

service:
  type: ClusterIP

